services:
  # Development PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mdc_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: mpix_db
      POSTGRES_USER: mpix_user
      POSTGRES_PASSWORD: mpix_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mpix_user -d mpix_db"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mdc_dev_network

  # Development Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mdc_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - mdc_dev_network

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  mdc_dev_network:
    driver: bridge